In [2]:
import numpy as np
import pandas as pd

### Australian datasets - application cost

In [6]:
adapt_cost = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPadapt_cost_total.csv',
                           delimiter  = ',')
x_adapt = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a_whole_scale.csv', 
                    delimiter = ',', usecols = (19,20,21,22), skip_header=1)

install_cost = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPinstall_cost_total.csv',
                           delimiter  = ',')
x_install = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a_whole_scale.csv', 
                    delimiter = ',', usecols = (10,11,12,13,14), skip_header=1)

train_cost = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPtrain_cost_total.csv',
                           delimiter  = ',')
x_train = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a_whole_scale.csv', 
                    delimiter = ',', usecols = (15,16,17,18), skip_header=1)

intang_improve = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPintang_improve_total.csv',
                           delimiter  = ',')
x_intang = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a_whole_scale.csv', 
                    delimiter = ',', usecols = (1,7,9), skip_header=1)

product_improve = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPproduct_improve_total.csv',
                           delimiter  = ',')
x_prod = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a_whole_scale.csv', 
                    delimiter = ',', usecols = (2,3,4,5,6), skip_header=1)

In [7]:
adapt_bar = np.mean(x_adapt, axis = 1).reshape(98,1);
install_bar = np.mean(x_install, axis = 1).reshape(98,1);
train_bar = np.mean(x_train, axis = 1).reshape(98,1);
intang_bar = np.mean(x_intang, axis = 1).reshape(98,1);
product_bar = np.mean(x_prod, axis = 1).reshape(98,1);

In [8]:
adapt_cost_1 = adapt_cost*adapt_bar;
install_cost_1 = -install_cost*install_bar;
train_cost_1 = -train_cost*train_bar;
intang_improve_1 = -intang_improve*intang_bar;
product_improve_1 = -product_improve*product_bar;

In [9]:
np.savetxt('APPadapt_cost_AU_avg_whole.csv', adapt_cost_1,delimiter=', ')
np.savetxt('APPinstall_cost_AU_avg_whole.csv', install_cost_1,delimiter=', ')
np.savetxt('APPtrain_cost_AU_avg_whole.csv', train_cost_1,delimiter=', ')
np.savetxt('APPintang_improve_AU_avg_whole.csv', intang_improve_1,delimiter=', ')
np.savetxt('APPproduct_improve_AU_avg_whole.csv', product_improve_1,delimiter=', ')

In [20]:
adapt_cost_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPadapt_cost_AU_avg_whole.csv',
                           delimiter  = ',')
install_cost_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPinstall_cost_AU_avg_whole.csv',
                           delimiter  = ',')
train_cost_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPtrain_cost_AU_avg_whole.csv',
                           delimiter  = ',')
intang_improve_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPintang_improve_AU_avg_whole.csv',
                           delimiter  = ',')
product_improve_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/APPproduct_improve_AU_avg_whole.csv',
                           delimiter  = ',')
print ('Adapt C',adapt_cost_1[83,:])
print ('Install C', install_cost_1[83,:])
print ('Train C',train_cost_1[83,:])
print ('Intang Improve', intang_improve_1[83,:])
print ('Product Improve', product_improve_1[83,:])
print (intang_improve_1.shape)

Adapt C [-0.32826413 -0.18557155 -0.20005161 -0.0979616  -0.24932694 -0.24184957
 -0.20010855]
Install C [ 10.94911995   5.90396531   9.68731971   3.7742238    4.94882877
  11.19171864   8.45365035]
Train C [ 0.19726198 -0.30144581 -0.44920949  0.22552971 -0.53042512 -0.38703566
 -0.10265946]
Intang Improve [-0.03501383 -2.37831051 -2.01579056 -0.57754575 -0.83827126 -0.6942261
 -1.12134484]
Product Improve [-13.83461156 -15.45471612 -19.19355472 -15.83063879 -16.68674174
 -14.29595682 -13.57546455]
(98, 7)


In [21]:
i = 0;
j = 0;
total_cost = np.zeros((98,7))
for i in range (98):
    for j in range (7):
        total_cost_1 = adapt_cost_1.item((i, j))+install_cost_1.item((i, j))+train_cost_1.item((i,j))-intang_improve_1.item((i,j))-product_improve_1.item((i,j));
        np.put(total_cost, [7*i+j], [total_cost_1])
np.savetxt('Application_cost_AU_avg_whole.csv', total_cost, delimiter=',') 

### Australian datasets - LOD cost

In [5]:
adapt_cost_LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/y_cost_LODadapt_cost.csv',
                           delimiter  = ',')
install_cost_LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/y_cost_LODinstall_cost.csv',
                           delimiter  = ',')
train_cost_LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/y_cost_LODtrain_cost.csv',
                           delimiter  = ',')
intang_improve_LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/y_cost_LODintang_improve.csv',
                           delimiter  = ',')
product_improve_LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/y_cost_LODproduct_improve.csv',
                           delimiter  = ',')
train_b = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv', 
                    delimiter = ',', usecols = (15,16,17,18), skip_header=1)
intang_b = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv', 
                    delimiter = ',', usecols = (2,3,4,5,6), skip_header=1)
adapt_b = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv', 
                    delimiter = ',', usecols = (19,20,21,22), skip_header=1)
install_b = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv', 
                    delimiter = ',', usecols = (10,11,12,13,14), skip_header=1)


In [23]:
adapt_cost_2 = adapt_cost_LOD*adapt_bar;
install_cost_2 = -install_cost_LOD*install_bar;
train_cost_2 = -train_cost_LOD*train_bar;
intang_improve_2 = -intang_improve_LOD*intang_bar;
product_improve_2 = -product_improve_LOD*product_bar;

ValueError: operands could not be broadcast together with shapes (14,4) (98,1) 

In [14]:
np.savetxt('y_cost_LODadapt_cost_AU_avg.csv', adapt_cost_2,delimiter=', ')
np.savetxt('y_cost_LODinstall_cost_AU_avg.csv', install_cost_2,delimiter=', ')
np.savetxt('y_cost_LODtrain_cost_AU_avg.csv', train_cost_2,delimiter=', ')
np.savetxt('y_cost_LODintang_improve_AU_avg.csv', intang_improve_2,delimiter=', ')
np.savetxt('y_cost_LODproduct_improve_AU_avg.csv', product_improve_2,delimiter=', ')

NameError: name 'adapt_cost_2' is not defined

In [11]:
i = 0;
j = 0;
total_cost_LOD = np.zeros((14,4))
for i in range (14):
    for j in range (4):
        total_cost_1_LOD = adapt_cost_2.item((i, j))+install_cost_2.item((i, j))+train_cost_2.item((i,j))-intang_improve_2.item((i,j))-product_improve_2.item((i,j));
        np.put(total_cost_LOD, [4*i+j], [total_cost_1_LOD]) 
np.savetxt('LOD_cost_AU_avg.csv', total_cost_LOD, delimiter=',')

### Australian datasets - LOD cost for a specific application

In [3]:
application = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/Application_cost_AU_avg.csv',
                           delimiter  = ',')
LOD = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Jupyter/Keras/LOD_cost_AU_avg.csv', delimiter  = ',')

i = 0;
j = 0;
k = 0;
TC13 = np.zeros((98,4));
for i in range (14):
    for j in range (7):
        for k in range (4):
            TC_1 = application.item((i,j))*LOD.item((i,k));
            #TC_2 = 10*j + k;
            np.put(TC13, [(4*j+k)*(i+1)], [TC_1])

#TC = np.vstack((TC1,TC2,TC3,TC4,TC5,TC6,TC7,TC8,TC9,TC10,TC11,TC12,TC13))
print(TC13.shape)
np.savetxt('LOD_APP_AU_avg.csv', TC13, delimiter=',')

In [4]:
au_6app = application[[5],:].reshape(7,1)
au_6lod = LOD[[5],:].reshape(4,1)

In [5]:
au_6app

array([[ 30.09362393],
       [ -6.92389194],
       [  1.4974309 ],
       [ -4.29339801],
       [ -4.36176528],
       [ 21.87264613],
       [ 15.16563019]])

In [17]:
au_6lod

array([[ 1.42589904],
       [-1.54127238],
       [ 3.19242722],
       [ 4.99968954]])

In [14]:
i = 0;
j = 0;
TC = np.zeros((7,4))
for i in range (7):
    for j in range (4):
        x = au_6app.item((i,0))+au_6lod.item((j,0));
        np.put(TC, [4*i+j], [x])
print (TC)

[[ 31.51952297  28.55235155  33.28605115  35.09331347]
 [ -5.4979929   -8.46516432  -3.73146472  -1.9242024 ]
 [  2.92332994  -0.04384148   4.68985811   6.49712043]
 [ -2.86749897  -5.83467039  -1.10097079   0.70629153]
 [ -2.93586624  -5.90303766  -1.16933806   0.63792426]
 [ 23.29854517  20.33137375  25.06507334  26.87233566]
 [ 16.59152924  13.62435781  18.35805741  20.16531973]]
