In [1]:
from __future__ import print_function
import numpy as np
import tensorflow as tf
import h5py
import keras.backend as K
from keras.models import Sequential, Model, model_from_json
from keras.layers import Dense, Activation
from keras import optimizers, layers, callbacks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

Using TensorFlow backend.


## Installation and maintenance cost (IM6, CB8, OS3, IM4, IM5)

In [2]:
x_1 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_train_scale.csv', 
                    delimiter = ',', usecols = (10,11,12,13,14), skip_header=2)
y_1o = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_train_scale.csv', 
                   delimiter =',', usecols = (29), skip_header=2).reshape (54,1)
x_2 = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv', 
                    delimiter = ',', usecols = (10,11,12,13,14), skip_header=1)
y_2o = np.genfromtxt ('C:/Users/z5023853/OneDrive - UNSW/Separated dataset_ML/a1_cv_scale.csv',
                      delimiter =',', usecols = (29),skip_header=1).reshape (14,1)

In [3]:
enc = OneHotEncoder ()
enc.fit (y_1o)
y_1 = enc.transform(y_1o).toarray()
y_2 = enc.transform(y_2o).toarray()

In [4]:
y_whole = np.vstack ((y_1, y_2)).astype(np.float32)
x_whole = np.vstack ((x_1, x_2)).astype(np.float32)
x_traind = x_1
x_test = x_2
y_traind = y_1
y_test = y_2
x_train, x_cv, y_train, y_cv = train_test_split (x_1,y_1,test_size=0.13)

In [5]:
num_classes = 4;

model = Sequential ()
model.add (Dense (units = 11, input_dim = 5))
model.add (layers.Activation ('tanh'))
model.add (Dense (units = 11))
#model.add (layers.Activation ('tanh'))
#model.add (Dense (units = 11))
#model.add (layers.Activation ('tanh'))
#model.add (Dense (units = 16))
model.add (Dense(num_classes, activation = 'softmax'))

#sgd = optimizer.SGD (lr=0.01, momentum = 0, decay =0, nestrov = False)
model.compile (loss = 'binary_crossentropy', optimizer = 'sgd', 
               metrics=['binary_accuracy'])

History = model.fit(x_train, y_train,
                    batch_size=60,
                    epochs=45,
                    verbose=1, validation_data=(x_cv, y_cv))

print(model.evaluate (x_test, y_test, batch_size = 60, verbose =1))

#help (model.evaluate)
#this is the output units

y_pred_train = model.predict (x_train)
y_pred_cv = model.predict (x_cv)
y_pred_test = model.predict (x_test)
y_pred_whole = np.vstack ((y_pred_train, y_pred_cv, y_pred_test)).astype(np.float32)

Train on 46 samples, validate on 8 samples
Epoch 1/45
46/46 [==============================] - ETA: 0s - loss: 0.5786 - binary_accuracy: 0.7500 - val_loss: 0.5458 - val_binary_accuracy: 0.7812
Epoch 2/45
46/46 [==============================] - ETA: 0s - loss: 0.5782 - binary_accuracy: 0.7500 - val_loss: 0.5456 - val_binary_accuracy: 0.7812
Epoch 3/45
46/46 [==============================] - ETA: 0s - loss: 0.5778 - binary_accuracy: 0.7500 - val_loss: 0.5454 - val_binary_accuracy: 0.7812
Epoch 4/45
46/46 [==============================] - ETA: 0s - loss: 0.5775 - binary_accuracy: 0.7500 - val_loss: 0.5452 - val_binary_accuracy: 0.7812
Epoch 5/45
46/46 [==============================] - ETA: 0s - loss: 0.5771 - binary_accuracy: 0.7500 - val_loss: 0.5451 - val_binary_accuracy: 0.7812
Epoch 6/45
46/46 [==============================] - ETA: 0s - loss: 0.5767 - binary_accuracy: 0.7500 - val_loss: 0.5449 - val_binary_accuracy: 0.7812
Epoch 7/45
46/46 [==============================] - ETA: 

### t(x) for labelling

In [6]:
#save model to json, weights to HDF5
model_json = model.to_json ()
with open ('model_lod_install_cost_a.json', 'w') as json_file:
    json_file.write(model_json)
model.save_weights('model_lod_install_cost_a.h5')
print ('Saved model to disk')

Saved model to disk


In [5]:
#load json and create model
json_file = open('model_lod_install_cost_a.json', 'r')
loaded_model_json = json_file.read ()
json_file.close ()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights('model_lod_install_cost_a.h5')

In [6]:
loaded_model.compile(loss = 'binary_crossentropy', optimizer = 'sgd', 
               metrics=['binary_accuracy'])
print(loaded_model.evaluate (x_test, y_test, batch_size = 20, verbose =1))
y_pred_test = loaded_model.predict (x_test)
print(y_pred_test)

14/14 [==============================] - ETA: 0s
[0.49672415852546692, 0.75]
[[ 0.12999903  0.18525609  0.24813689  0.43660805]
 [ 0.3052786   0.41167802  0.12271223  0.16033116]
 [ 0.22536397  0.33230707  0.25222477  0.1901042 ]
 [ 0.26198256  0.2689375   0.29300255  0.17607746]
 [ 0.25923961  0.10333741  0.37598932  0.26143369]
 [ 0.1730022   0.13998917  0.27344149  0.41356713]
 [ 0.19649552  0.14710993  0.35660958  0.29978496]
 [ 0.1829896   0.12966707  0.30954888  0.37779444]
 [ 0.24978064  0.24108757  0.21374774  0.29538402]
 [ 0.2188601   0.18396661  0.22129524  0.37587801]
 [ 0.27930412  0.38728058  0.16892855  0.16448675]
 [ 0.2629241   0.1720839   0.31442046  0.25057152]
 [ 0.28291994  0.21974184  0.30438513  0.19295309]
 [ 0.31106907  0.39985302  0.16039935  0.12867856]]


In [7]:
i = 0;
j = 0;
m = np.zeros((14,4));
for i in range (14):
    max = 0.0000001;
    for j in range (4):
        if y_pred_test.item ((i,j))>=max:
            max = y_pred_test.item ((i,j))
    for j in range (4):
        if y_pred_test.item ((i,j)) ==max:
            np.put(m, [4*i+j], [1])

i = 0;
j = 0;
selected_LOD = np.zeros((14,1));
for i in range (14):
    for j in range (4):
        if m.item((i,j))>0:
            selected_LOD_1 = m.item((i,j))*y_pred_test.item((i,j));
            np.put(selected_LOD, [i], [selected_LOD_1])

i = 0;
j = 0;
cf = np.zeros((14,4))
for i in range (14):
    for j in range (4):
        cf_1 = y_pred_test.item((i,j))-selected_LOD.item((i,0));
        cf_2 = 10*cf_1;
        np.put(cf, [4*i+j], [cf_2])
print (cf)
np.savetxt('y_cost_LODinstall_cost.csv', cf, delimiter=',') 

[[-3.0660902  -2.51351953 -1.88471153  0.        ]
 [-1.06399417  0.         -2.88965784 -2.51346856]
 [-1.06943101  0.         -0.80082297 -1.42202869]
 [-0.31019986 -0.24065048  0.         -1.16925091]
 [-1.16749704 -2.72651911  0.         -1.14555627]
 [-2.40564927 -2.73577958 -1.40125632  0.        ]
 [-1.60114065 -2.09499657  0.         -0.56824625]
 [-1.94804847 -2.48127371 -0.6824556   0.        ]
 [-0.4560338  -0.54296449 -0.8163628   0.        ]
 [-1.57017902 -1.91911399 -1.54582769  0.        ]
 [-1.07976466  0.         -2.18352035 -2.22793832]
 [-0.51496357 -1.42336562  0.         -0.63848943]
 [-0.21465182 -0.84643289  0.         -1.11432031]
 [-0.8878395   0.         -2.39453673 -2.71174461]]
